### ISSUE TITLE
你这个程序很神奇诶

### ISSUE THREAD

**Issue by luckypoem** [LuoZijun/python-proxy#1]
不过访问youtube很慢，几乎打不开。你能用你这个程序打开www.youtube.com吗？
怎样改善，才能打开youtube?

另外在readme中，还是把“填上 代理地址： 127.0.0.1 ”改为 “填上 代理地址： 你的服务器的ip地址“，免得造成误会，我刚开始时，就被误导了，填写了127.0.0.1

**Comment by LuoZijun** [comment]
@luckypoem 你好，这个是我年少时写的代码。

已经不维护了，现在推荐使用更好的 https://github.com/LuoZijun/exodus

**Comment by luckypoem** [comment]
哦，用chrome+switchyomega,就可在chrome里看youtube了

**Comment by LuoZijun** [comment]
@luckypoem 是的，因为他是个 Socks5 代理。需要在浏览器设置 socks5 代理地址。

**Comment by LuoZijun** [comment]
> 另外在readme中，还是把“填上 代理地址： 127.0.0.1 ”改为 “填上 代理地址： 你的服务器的ip地址“，免得造成误会，我刚开始时，就被误导了，填写了127.0.0.1

代理地址默认就是监听在本地的 `127.0.0.1:1070` 所以，填写 `127.0.0.1` 并没有问题呀。

**Comment by luckypoem** [comment]
你这个“本地”是指本地机器吗？如果是的，那么代理地址应该填写服务器的公网ip才对吧？

**Comment by LuoZijun** [comment]
@luckypoem `SOCKS5` 是明文代理协议，这意味着如果你部署在 `境外网络` ，然后试图通过这个协议 实现 代理 `敏感内容` 的功能，这显然是不现实的。传输通道并不安全。

一个典型的正确 代理或者虚拟局域网架构是:

* 通过 `SOCKS5` 协议或者 利用 `TUN`  之类的技术收集客户机的流量信息。
* 将收集到的网络流量 做加密处理， 然后发送到 境外网络。

**Comment by luckypoem** [comment]
既然SOCKS代理是明文代理协议，那你这个SOCKS代理服务器程序又怎么能用来翻墙的呢？是做了流量混淆处理吗？

**Comment by LuoZijun** [comment]
@luckypoem 建议去了解下审查策略。
